
import { Item, EquipmentSlot, NpcType, SkillType, Vocation, DamageType } from '../../types';
import { IMG_BASE } from '../config';

export const AXE_LIST: Item[] = [
  { id: 'hand_axe', name: 'Hand Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 15, defense: 10, price: 80, sellPrice: 4, soldTo: [NpcType.TRADER], description: 'Machado pequeno.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Hand_Axe.gif` },
  { id: 'axe', name: 'Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 12, defense: 6, price: 20, sellPrice: 7, soldTo: [NpcType.TRADER], description: 'Machado simples.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Axe.gif` },
  { id: 'orcish_axe', name: 'Orcish Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 23, defense: 12, price: 0, sellPrice: 350, soldTo: [NpcType.GREEN_DJINN], description: 'Machado orc.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Orcish_Axe.gif` },
  { id: 'dwarven_axe', name: 'Dwarven Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 27, defense: 16, price: 0, sellPrice: 500, soldTo: [NpcType.TRADER], description: 'Machado anão.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Dwarven_Axe.gif` },
  { id: 'barbarian_axe', name: 'Barbarian Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 28, defense: 18, price: 0, sellPrice: 590, soldTo: [NpcType.GREEN_DJINN], description: 'Machado bárbaro.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Barbarian_Axe.gif` },
  { id: 'beastslayer_axe', name: 'Beastslayer Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 29, defense: 14, price: 0, sellPrice: 1500, soldTo: [NpcType.RASHID], description: 'Caçador de feras.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Beastslayer_Axe.gif` },
  { id: 'knight_axe', name: 'Knight Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 33, defense: 21, price: 2000, sellPrice: 900, soldTo: [NpcType.GREEN_DJINN], description: 'Machado de cavaleiro.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Knight_Axe.gif` },
  { id: 'double_axe', name: 'Double Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 35, defense: 12, price: 0, sellPrice: 260, soldTo: [NpcType.TRADER], description: 'Machado duplo.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Double_Axe.gif` },
  { id: 'halberd', name: 'Halberd', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 35, defense: 14, price: 400, sellPrice: 150, soldTo: [NpcType.TRADER], description: 'Alabarda.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Halberd.gif` },
  { id: 'headchopper', name: 'Headchopper', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 36, defense: 10, price: 0, sellPrice: 3000, soldTo: [NpcType.RASHID], description: 'Cortador de cabeças.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Headchopper.gif` },
  { id: 'fire_axe', name: 'Fire Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 38, defense: 16, price: 8000, sellPrice: 2800, soldTo: [NpcType.BLUE_DJINN], description: 'Machado de fogo.', scalingStat: SkillType.AXE, damageType: DamageType.FIRE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Fire_Axe.gif` },
  { id: 'noble_axe', name: 'Noble Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 39, defense: 22, price: 0, sellPrice: 10000, soldTo: [NpcType.RASHID], description: 'Machado nobre.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Noble_Axe.gif` },
  { id: 'dreaded_cleaver', name: 'Dreaded Cleaver', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 40, defense: 19, price: 0, sellPrice: 10000, soldTo: [NpcType.RASHID], description: 'Cutelo temido.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Dreaded_Cleaver.gif` },
  { id: 'vile_axe', name: 'Vile Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 46, defense: 20, price: 0, sellPrice: 30000, soldTo: [NpcType.RASHID], description: 'Machado vil.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Vile_Axe.gif` },
  { id: 'guardian_halberd', name: 'Guardian Halberd', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 46, defense: 15, price: 0, sellPrice: 11000, soldTo: [NpcType.GREEN_DJINN], description: 'Alabarda Guardiã.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Guardian_Halberd.gif` },
  { id: 'dragon_lance', name: 'Dragon Lance', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 47, defense: 16, price: 0, sellPrice: 9000, soldTo: [NpcType.GREEN_DJINN], description: 'Lança de dragão (2-Mãos).', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Dragon_Lance.gif` },
  { id: 'royal_axe', name: 'Royal Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 47, defense: 25, price: 0, sellPrice: 40000, soldTo: [NpcType.RASHID], description: 'Machado real.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Royal_Axe.gif` },
  { id: 'stonecutter_axe', name: 'Stonecutter Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 30, price: 0, sellPrice: 50000, soldTo: [NpcType.RASHID], description: 'Lendário SCA.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Stonecutter_Axe.gif` },
  { id: 'axe_of_destruction', name: 'Axe of Destruction', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 51, defense: 26, price: 0, sellPrice: 40000, soldTo: [NpcType.RASHID], description: 'Destruição Imbuída.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Axe_of_Destruction.gif` },
  { id: 'hellforged_axe', name: 'Hellforged Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 51, defense: 28, price: 0, sellPrice: 60000, soldTo: [NpcType.RASHID], description: 'Forjado no inferno.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Hellforged_Axe.gif` },
  { id: 'cobra_axe', name: 'Cobra Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 52, defense: 28, price: 0, sellPrice: 150000, soldTo: [NpcType.RASHID], description: 'Machado Cobra.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], damageType: DamageType.ICE, image: `${IMG_BASE}Cobra_Axe.gif` },
  { id: 'souleater', name: 'Souleater', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 55, defense: 31, price: 0, sellPrice: 500000, soldTo: [NpcType.RASHID], description: 'Devorador de Almas.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], damageType: DamageType.ICE, image: `${IMG_BASE}Souleater.gif` },
  { id: 'falcon_battleaxe', name: 'Falcon Battleaxe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 55, defense: 33, price: 0, sellPrice: 200000, soldTo: [NpcType.RASHID], description: 'Machado do Falcão.', scalingStat: SkillType.AXE, damageType: DamageType.ENERGY, image: `${IMG_BASE}Falcon_Battleaxe.gif` },
  { id: 'sanguine_hatchet', name: 'Sanguine Hatchet', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 61, defense: 33, price: 0, sellPrice: 1000000, soldTo: [NpcType.RASHID], description: 'Machadinha Sanguínea.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Sanguine_Hatchet.gif` },
  { id: 'grand_sanguine_hatchet', name: 'Grand Sanguine Hatchet', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 63, defense: 35, price: 0, sellPrice: 5000000, soldTo: [NpcType.RASHID], description: 'Machado Supremo.', scalingStat: SkillType.AXE, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Grand_Sanguine_Hatchet.gif` },
  { id: 'glaive', name: 'Glaive', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 18, price: 0, sellPrice: 15000, soldTo: [NpcType.RASHID], description: 'A throwing axe type.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Glaive.gif` },
  { id: 'bonebreaker', name: 'Bonebreaker', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 46, defense: 12, price: 0, sellPrice: 10000, soldTo: [NpcType.RASHID], description: 'Breaks bones.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Bonebreaker.gif` },
  { id: 'titan_axe', name: 'Titan Axe', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 45, defense: 22, price: 0, sellPrice: 15000, soldTo: [NpcType.RASHID], description: 'Axe of the Titans.', scalingStat: SkillType.AXE, image: `${IMG_BASE}Titan_Axe.gif` },
];
