
import { Item, EquipmentSlot, NpcType, SkillType, Vocation, DamageType } from '../../types';
import { IMG_BASE } from '../config';

export const CLUB_LIST: Item[] = [
  { id: 'club', name: 'Club', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 7, defense: 5, price: 1, sellPrice: 1, soldTo: [NpcType.TRADER], description: 'Um pedaço de madeira.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Club.gif` },
  { id: 'bone_club', name: 'Bone Club', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 12, defense: 8, price: 0, sellPrice: 20, soldTo: [NpcType.TRADER], description: 'Clava de osso.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Bone_Club.gif` },
  { id: 'mace', name: 'Mace', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 16, defense: 11, price: 90, sellPrice: 30, soldTo: [NpcType.TRADER], description: 'Uma maça de metal.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Mace.gif` },
  { id: 'battle_hammer', name: 'Battle Hammer', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 24, defense: 14, price: 350, sellPrice: 120, soldTo: [NpcType.TRADER], description: 'Martelo de batalha.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Battle_Hammer.gif` },
  { id: 'morning_star', name: 'Morning Star', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 25, defense: 11, price: 430, sellPrice: 100, soldTo: [NpcType.TRADER], description: 'Estrela da manhã.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Morning_Star.gif` },
  { id: 'furry_club', name: 'Furry Club', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 26, defense: 18, price: 0, sellPrice: 1000, soldTo: [NpcType.BLUE_DJINN], description: 'Clava peluda.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Furry_Club.gif` },
  { id: 'clerical_mace', name: 'Clerical Mace', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 28, defense: 15, price: 540, sellPrice: 170, soldTo: [NpcType.BLUE_DJINN], description: 'Maça clerical.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Clerical_Mace.gif` },
  { id: 'diamond_sceptre', name: 'Diamond Sceptre', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 31, defense: 17, price: 0, sellPrice: 3000, soldTo: [NpcType.GREEN_DJINN], description: 'Cetro de diamante.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Diamond_Sceptre.gif` },
  { id: 'dragon_hammer', name: 'Dragon Hammer', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 32, defense: 20, price: 2000, sellPrice: 2000, soldTo: [NpcType.GREEN_DJINN], description: 'Martelo de dragão.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Dragon_Hammer.gif` },
  { id: 'skull_staff', name: 'Skull Staff', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 36, defense: 12, price: 0, sellPrice: 6000, soldTo: [NpcType.GREEN_DJINN], description: 'Cajado leve e forte.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Skull_Staff.gif` },
  { id: 'shadow_sceptre', name: 'Shadow Sceptre', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 42, defense: 18, price: 0, sellPrice: 15000, soldTo: [NpcType.RASHID], description: 'Cetro das sombras.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Shadow_Sceptre.gif` },
  { id: 'cranial_basher', name: 'Cranial Basher', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 44, defense: 20, price: 0, sellPrice: 30000, soldTo: [NpcType.RASHID], description: 'Esmagador de crânios.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Cranial_Basher.gif` },
  { id: 'war_hammer', name: 'War Hammer', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 45, defense: 10, price: 0, sellPrice: 1200, soldTo: [NpcType.BLUE_DJINN], description: 'Martelo de guerra (2-Mãos).', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}War_Hammer.gif` },
  { id: 'onyx_flail', name: 'Onyx Flail', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 45, defense: 18, price: 0, sellPrice: 25000, soldTo: [NpcType.RASHID], description: 'Mangual de ônix.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Onyx_Flail.gif` },
  { id: 'heavy_mace', name: 'Heavy Mace', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 49, defense: 15, price: 0, sellPrice: 50000, soldTo: [NpcType.RASHID], description: 'Maça pesada.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Heavy_Mace.gif` },
  { id: 'thunder_hammer', name: 'Thunder Hammer', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 49, defense: 35, price: 100000, sellPrice: 75000, soldTo: [NpcType.RASHID], description: 'A lenda dos anões.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Thunder_Hammer.gif` },
  { id: 'arcane_staff', name: 'Arcane Staff', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 30, price: 0, sellPrice: 30000, soldTo: [NpcType.RASHID], description: 'Cajado arcano.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Arcane_Staff.gif` },
  { id: 'obsidian_truncheon', name: 'Obsidian Truncheon', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 30, price: 0, sellPrice: 65000, soldTo: [NpcType.RASHID], description: 'Porrete de obsidiana.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Obsidian_Truncheon.gif` },
  { id: 'mace_of_destruction', name: 'Mace of Destruction', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 51, defense: 26, price: 0, sellPrice: 40000, soldTo: [NpcType.RASHID], description: 'Destruição Imbuída.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Mace_of_Destruction.gif` },
  { id: 'cobra_club', name: 'Cobra Club', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 51, defense: 29, price: 0, sellPrice: 150000, soldTo: [NpcType.RASHID], description: 'Clava Cobra.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], damageType: DamageType.FIRE, image: `${IMG_BASE}Cobra_Club.gif` },
  { id: 'soulcrusher', name: 'Soulcrusher', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 54, defense: 32, price: 0, sellPrice: 500000, soldTo: [NpcType.RASHID], description: 'Esmagador de Almas.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], damageType: DamageType.ICE, image: `${IMG_BASE}Soulcrusher.gif` },
  { id: 'falcon_mace', name: 'Falcon Mace', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 55, defense: 33, price: 0, sellPrice: 250000, soldTo: [NpcType.RASHID], description: 'Maça do Falcão.', scalingStat: SkillType.CLUB, damageType: DamageType.ENERGY, image: `${IMG_BASE}Falcon_Mace.gif` },
  { id: 'sanguine_bludgeon', name: 'Sanguine Bludgeon', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 61, defense: 34, price: 0, sellPrice: 1000000, soldTo: [NpcType.RASHID], description: 'Porrete Sanguíneo.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Sanguine_Bludgeon.gif` },
  { id: 'grand_sanguine_bludgeon', name: 'Grand Sanguine Bludgeon', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 63, defense: 36, price: 0, sellPrice: 5000000, soldTo: [NpcType.RASHID], description: 'Impacto Supremo.', scalingStat: SkillType.CLUB, requiredVocation: [Vocation.KNIGHT], image: `${IMG_BASE}Grand_Sanguine_Bludgeon.gif` },
  { id: 'spiked_squalidr', name: 'Spiked Squalidr', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 30, price: 0, sellPrice: 5000, soldTo: [NpcType.RASHID], description: 'A spiked club.', scalingStat: SkillType.CLUB, image: `${IMG_BASE}Spiked_Squalidr.gif` },
];
