
import { Item, EquipmentSlot, NpcType, SkillType, Vocation } from '../../types';
import { IMG_BASE } from '../config';

export const DISTANCE_LIST: Item[] = [
  { id: 'spear', name: 'Spear', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 25, defense: 0, price: 10, sellPrice: 3, soldTo: [NpcType.TRADER], description: 'Arma de arremesso.', scalingStat: SkillType.DISTANCE, requiredVocation: [Vocation.PALADIN], image: `${IMG_BASE}Spear.gif` },
  { id: 'bow', name: 'Bow', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 400, sellPrice: 100, soldTo: [NpcType.TRADER], description: 'Arco simples.', scalingStat: SkillType.DISTANCE, weaponType: 'bow', requiredVocation: [Vocation.PALADIN], image: `${IMG_BASE}Bow.gif` },
  { id: 'crossbow', name: 'Crossbow', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 500, sellPrice: 120, soldTo: [NpcType.TRADER], description: 'Besta simples.', scalingStat: SkillType.DISTANCE, weaponType: 'crossbow', requiredVocation: [Vocation.PALADIN], image: `${IMG_BASE}Crossbow.gif` },
  { id: 'elvish_bow', name: 'Elvish Bow', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 2000, sellPrice: 500, soldTo: [NpcType.BLUE_DJINN], description: 'Arco preciso.', scalingStat: SkillType.DISTANCE, weaponType: 'bow', requiredVocation: [Vocation.PALADIN], image: `${IMG_BASE}Elvish_Bow.gif` },
  { id: 'arbalest', name: 'Arbalest', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 0, sellPrice: 10000, soldTo: [NpcType.GREEN_DJINN], description: 'Besta pesada.', scalingStat: SkillType.DISTANCE, weaponType: 'crossbow', requiredVocation: [Vocation.PALADIN], image: `${IMG_BASE}Arbalest.gif` },
  { id: 'royal_spear', name: 'Royal Spear', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 35, defense: 0, price: 15, sellPrice: 5, soldTo: [NpcType.TRADER], description: 'Lança real.', scalingStat: SkillType.DISTANCE, requiredVocation: [Vocation.PALADIN], requiredLevel: 25, image: `${IMG_BASE}Royal_Spear.gif` },
  { id: 'composite_hornbow', name: 'Composite Hornbow', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 0, sellPrice: 25000, soldTo: [NpcType.RASHID], description: 'Arco composto.', scalingStat: SkillType.DISTANCE, weaponType: 'bow', requiredVocation: [Vocation.PALADIN], requiredLevel: 50, image: `${IMG_BASE}Composite_Hornbow.gif` },
  { id: 'thorn_spitter', name: 'Thorn Spitter', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 0, sellPrice: 80000, soldTo: [NpcType.RASHID], description: 'Dispara espinhos.', scalingStat: SkillType.DISTANCE, weaponType: 'crossbow', requiredVocation: [Vocation.PALADIN], requiredLevel: 100, image: `${IMG_BASE}Thorn_Spitter.gif` },
  { id: 'chain_bolter', name: 'Chain Bolter', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 0, sellPrice: 60000, soldTo: [NpcType.RASHID], description: 'Besta de corrente.', scalingStat: SkillType.DISTANCE, weaponType: 'crossbow', requiredVocation: [Vocation.PALADIN], requiredLevel: 80, image: `${IMG_BASE}Chain_Bolter.gif` },
  { id: 'cobra_crossbow', name: 'Cobra Crossbow', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 0, defense: 0, price: 0, sellPrice: 200000, soldTo: [NpcType.RASHID], description: 'Cobra Crossbow.', weaponType: 'crossbow', scalingStat: SkillType.DISTANCE, image: `${IMG_BASE}Cobra_Crossbow.gif` },
];
