
import { Item, NpcType } from '../../types';
import { IMG_BASE } from '../config';

export const PRODUCTS_LIST: Item[] = [
  // Creature Products
  { id: 'meat', name: 'Meat', type: 'loot', price: 0, sellPrice: 2, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Raw meat.', image: `${IMG_BASE}Meat.gif` },
  { id: 'ham', name: 'Ham', type: 'loot', price: 0, sellPrice: 8, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Huge chunk of meat.', image: `${IMG_BASE}Ham.gif` },
  { id: 'cheese', name: 'Cheese', type: 'loot', price: 0, sellPrice: 2, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'A piece of cheese.', image: `${IMG_BASE}Cheese.gif` },
  { id: 'wolf_paw', name: 'Wolf Paw', type: 'loot', price: 0, sellPrice: 70, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Paw of a wolf.', image: `${IMG_BASE}Wolf_Paw.gif` },
  { id: 'bear_paw', name: 'Bear Paw', type: 'loot', price: 0, sellPrice: 100, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Paw of a bear.', image: `${IMG_BASE}Bear_Paw.gif` },
  { id: 'honeycomb', name: 'Honeycomb', type: 'loot', price: 0, sellPrice: 50, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Sweet honey.', image: `${IMG_BASE}Honeycomb.gif` },
  { id: 'skull', name: 'Skull', type: 'loot', price: 0, sellPrice: 20, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Human skull.', image: `${IMG_BASE}Skull.gif` },
  { id: 'cyclops_toe', name: 'Cyclops Toe', type: 'loot', price: 0, sellPrice: 55, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Valuable toe.', image: `${IMG_BASE}Cyclops_Toe.gif` },
  { id: 'vampire_dust', name: 'Vampire Dust', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Dust from a vampire.', image: `${IMG_BASE}Vampire_Dust.gif` },
  { id: 'spider_silk', name: 'Spider Silk', type: 'loot', price: 0, sellPrice: 8000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Strong silk.', image: `${IMG_BASE}Spider_Silk.gif` },
  { id: 'iron_ore', name: 'Iron Ore', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Heavy ore.', image: `${IMG_BASE}Iron_Ore.gif` },
  { id: 'green_dragon_leather', name: 'Green Dragon Leather', type: 'loot', price: 0, sellPrice: 100, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Skin of a dragon.', image: `${IMG_BASE}Green_Dragon_Leather.gif` },
  { id: 'red_dragon_leather', name: 'Red Dragon Leather', type: 'loot', price: 0, sellPrice: 200, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Skin of a DL.', image: `${IMG_BASE}Red_Dragon_Leather.gif` },
  { id: 'hardened_bone', name: 'Hardened Bone', type: 'loot', price: 0, sellPrice: 800, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Very hard bone.', image: `${IMG_BASE}Hardened_Bone.gif` },
  { id: 'demon_dust', name: 'Demon Dust', type: 'loot', price: 0, sellPrice: 5000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Remains of a demon.', image: `${IMG_BASE}Demon_Dust.gif` },
  { id: 'behemoth_fang', name: 'Behemoth Fang', type: 'loot', price: 0, sellPrice: 2500, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Big fang.', image: `${IMG_BASE}Behemoth_Fang.gif` },
  { id: 'hydra_head', name: 'Hydra Head', type: 'loot', price: 0, sellPrice: 600, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Head of a hydra.', image: `${IMG_BASE}Hydra_Head.gif` },
  { id: 'demon_horn', name: 'Demon Horn', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Horn of a demon.', image: `${IMG_BASE}Demon_Horn.gif` },
  { id: 'dragon_scale', name: 'Green Dragon Scale', type: 'loot', price: 0, sellPrice: 100, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Scale of a dragon.', image: `${IMG_BASE}Green_Dragon_Scale.gif` },
  { id: 'demonic_essence', name: 'Demonic Essence', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Essence of evil.', image: `${IMG_BASE}Demonic_Essence.gif` },
  { id: 'giant_cobra_scale', name: 'Giant Cobra Scale', type: 'loot', price: 0, sellPrice: 5000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Scale of a huge cobra.', image: `${IMG_BASE}Giant_Cobra_Scale.gif` },
  { id: 'moonlight_crystals', name: 'Moonlight Crystals', type: 'loot', price: 0, sellPrice: 1500, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Crystals.', image: `${IMG_BASE}Moonlight_Crystals.gif` },
  { id: 'nose_ring', name: 'Nose Ring', type: 'loot', price: 0, sellPrice: 1500, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Ring from Horned Fox.', image: `${IMG_BASE}Nose_Ring.gif` },
  { id: 'dragon_claw', name: 'Dragon Claw', type: 'loot', price: 0, sellPrice: 8000, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Claw from Demodras.', image: `${IMG_BASE}Dragon_Claw.gif` },
  { id: 'foxtail', name: 'Foxtail', type: 'loot', price: 0, sellPrice: 5000, soldTo: [NpcType.RASHID, NpcType.YASIR], description: 'Cauda de raposa.', image: `${IMG_BASE}Foxtail.gif` },
  { id: 'grave_flower', name: 'Grave Flower', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.RASHID, NpcType.YASIR], description: 'Flor de túmulo.', image: `${IMG_BASE}Grave_Flower.gif` },
  { id: 'grant_of_arms', name: 'Grant of Arms', type: 'loot', price: 0, sellPrice: 10000, soldTo: [NpcType.RASHID, NpcType.YASIR], description: 'Brasão.', image: `${IMG_BASE}Grant_of_Arms.gif` },
  { id: 'wyvern_talisman', name: 'Wyvern Talisman', type: 'loot', price: 0, sellPrice: 265, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'A talisman.', image: `${IMG_BASE}Wyvern_Talisman.gif` },
  { id: 'emerald_bangle', name: 'Emerald Bangle', type: 'loot', price: 0, sellPrice: 800, soldTo: [NpcType.RASHID, NpcType.YASIR], description: 'Green jewelry.', image: `${IMG_BASE}Emerald_Bangle.gif` },
  { id: 'ear_of_corym', name: 'Ear of a Corym', type: 'loot', price: 0, sellPrice: 40, soldTo: [NpcType.YASIR], description: 'An ear.', image: `${IMG_BASE}Ear_of_a_Corym.gif` },
  { id: 'cheesy_figurine', name: 'Cheesy Figurine', type: 'loot', price: 0, sellPrice: 150, soldTo: [NpcType.YASIR], description: 'Made of cheese.', image: `${IMG_BASE}Cheesy_Figurine.gif` },
  { id: 'frazzle_skin', name: 'Frazzle Skin', type: 'loot', price: 0, sellPrice: 400, soldTo: [NpcType.YASIR], description: 'Skin from Roshamuul.', image: `${IMG_BASE}Frazzle_Skin.gif` },
  { id: 'frazzle_tongue', name: 'Frazzle Tongue', type: 'loot', price: 0, sellPrice: 600, soldTo: [NpcType.YASIR], description: 'Tongue of a Frazzlemaw.', image: `${IMG_BASE}Frazzle_Tongue.gif` },
  { id: 'silencer_claws', name: 'Silencer Claws', type: 'loot', price: 0, sellPrice: 490, soldTo: [NpcType.YASIR], description: 'Claws that silence.', image: `${IMG_BASE}Silencer_Claws.gif` },
  { id: 'guzzlemaw_tongue', name: 'Guzzlemaw Tongue', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.YASIR], description: 'A large tongue.', image: `${IMG_BASE}Guzzlemaw_Tongue.gif` },
  { id: 'soul_orb', name: 'Soul Orb', type: 'loot', price: 0, sellPrice: 130, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'Used for mana.', image: `${IMG_BASE}Soul_Orb.gif` },
  { id: 'leather_harness', name: 'Leather Harness', type: 'loot', price: 0, sellPrice: 750, soldTo: [NpcType.YASIR], description: 'Sturdy harness.', image: `${IMG_BASE}Leather_Harness.gif` },
  { id: 'spiky_club', name: 'Spiky Club', type: 'loot', price: 0, sellPrice: 100, soldTo: [NpcType.TRADER, NpcType.YASIR], description: 'A primitive weapon.', image: `${IMG_BASE}Spiky_Club.gif` },
  { id: 'ogre_knuckles', name: 'Ogre Knuckles', type: 'loot', price: 0, sellPrice: 300, soldTo: [NpcType.YASIR], description: 'Knuckles of an Ogre.', image: `${IMG_BASE}Ogre_Knuckles.gif` },
  { id: 'onyx_chip', name: 'Onyx Chip', type: 'loot', price: 0, sellPrice: 400, soldTo: [NpcType.YASIR], description: 'Chip of onyx.', image: `${IMG_BASE}Onyx_Chip.gif` },
  { id: 'silencer_resonating_chamber', name: 'Silencer Resonating Chamber', type: 'loot', price: 0, sellPrice: 600, soldTo: [NpcType.YASIR], description: 'A strange organ.', image: `${IMG_BASE}Silencer_Resonating_Chamber.gif` },
  { id: 'cobra_tongue', name: 'Cobra Tongue', type: 'loot', price: 0, sellPrice: 1200, soldTo: [NpcType.YASIR], description: 'A tongue of a cobra.', image: `${IMG_BASE}Cobra_Tongue.gif` },
  
  // SMALL GEMS (Sold to Trader/Jeweller)
  { id: 'small_diamond', name: 'Small Diamond', type: 'loot', price: 0, sellPrice: 300, soldTo: [NpcType.TRADER], description: 'A small diamond.', image: `${IMG_BASE}Small_Diamond.gif` },
  { id: 'small_ruby', name: 'Small Ruby', type: 'loot', price: 0, sellPrice: 250, soldTo: [NpcType.TRADER], description: 'A small ruby.', image: `${IMG_BASE}Small_Ruby.gif` },
  { id: 'small_emerald', name: 'Small Emerald', type: 'loot', price: 0, sellPrice: 250, soldTo: [NpcType.TRADER], description: 'A small emerald.', image: `${IMG_BASE}Small_Emerald.gif` },
  { id: 'small_amethyst', name: 'Small Amethyst', type: 'loot', price: 0, sellPrice: 200, soldTo: [NpcType.TRADER], description: 'A small amethyst.', image: `${IMG_BASE}Small_Amethyst.gif` },
  { id: 'small_sapphire', name: 'Small Sapphire', type: 'loot', price: 0, sellPrice: 250, soldTo: [NpcType.TRADER], description: 'A small sapphire.', image: `${IMG_BASE}Small_Sapphire.gif` },
  { id: 'small_topaz', name: 'Small Topaz', type: 'loot', price: 0, sellPrice: 200, soldTo: [NpcType.TRADER], description: 'A small topaz.', image: `${IMG_BASE}Small_Topaz.gif` },

  // GEMS & PEARLS (Sold to Trader/Jeweller)
  { id: 'diamond', name: 'Diamond', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.TRADER], description: 'A valuable diamond.', image: `${IMG_BASE}Diamond.gif` },
  { id: 'ruby', name: 'Ruby', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.TRADER], description: 'A valuable ruby.', image: `${IMG_BASE}Ruby.gif` },
  { id: 'sapphire', name: 'Sapphire', type: 'loot', price: 0, sellPrice: 2500, soldTo: [NpcType.TRADER], description: 'A valuable sapphire.', image: `${IMG_BASE}Sapphire.gif` },
  { id: 'emerald', name: 'Emerald', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.TRADER], description: 'A valuable emerald.', image: `${IMG_BASE}Emerald.gif` },
  { id: 'amethyst', name: 'Amethyst', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.TRADER], description: 'A valuable amethyst.', image: `${IMG_BASE}Amethyst.gif` },
  { id: 'blue_gem', name: 'Blue Gem', type: 'loot', price: 0, sellPrice: 5000, soldTo: [NpcType.TRADER], description: 'A precious blue gem.', image: `${IMG_BASE}Blue_Gem.gif` },
  { id: 'green_gem', name: 'Green Gem', type: 'loot', price: 0, sellPrice: 5000, soldTo: [NpcType.TRADER], description: 'A precious green gem.', image: `${IMG_BASE}Green_Gem.gif` },
  { id: 'yellow_gem', name: 'Yellow Gem', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.TRADER], description: 'A precious yellow gem.', image: `${IMG_BASE}Yellow_Gem.gif` },
  { id: 'violet_gem', name: 'Violet Gem', type: 'loot', price: 0, sellPrice: 10000, soldTo: [NpcType.TRADER], description: 'A highly valuable violet gem.', image: `${IMG_BASE}Violet_Gem.gif` },
  { id: 'red_gem', name: 'Red Gem', type: 'loot', price: 0, sellPrice: 1000, soldTo: [NpcType.TRADER], description: 'A valuable red gem.', image: `${IMG_BASE}Red_Gem.gif` },
  { id: 'white_pearl', name: 'White Pearl', type: 'loot', price: 0, sellPrice: 160, soldTo: [NpcType.TRADER], description: 'A pretty pearl.', image: `${IMG_BASE}White_Pearl.gif` },
  { id: 'black_pearl', name: 'Black Pearl', type: 'loot', price: 0, sellPrice: 280, soldTo: [NpcType.TRADER], description: 'A rare black pearl.', image: `${IMG_BASE}Black_Pearl.gif` },
  { id: 'giant_shimmering_pearl', name: 'Giant Shimmering Pearl', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.TRADER], description: 'A giant pearl.', image: `${IMG_BASE}Giant_Shimmering_Pearl.gif` },
  { id: 'talon', name: 'Talon', type: 'loot', price: 0, sellPrice: 320, soldTo: [NpcType.TRADER, NpcType.RASHID], description: 'A dragon talon.', image: `${IMG_BASE}Talon.gif` },

  // VALUABLES (Rashid / Djinns)
  { id: 'gold_ingot', name: 'Gold Ingot', type: 'loot', price: 0, sellPrice: 5000, soldTo: [NpcType.RASHID], description: 'Solid gold.', image: `${IMG_BASE}Gold_Ingot.gif` },
  { id: 'draconian_steel', name: 'Piece of Draconian Steel', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.RASHID], description: 'Valuable steel.', image: `${IMG_BASE}Piece_of_Draconian_Steel.gif` },
  { id: 'hell_steel', name: 'Piece of Hell Steel', type: 'loot', price: 0, sellPrice: 3000, soldTo: [NpcType.RASHID], description: 'Infernal steel.', image: `${IMG_BASE}Piece_of_Hell_Steel.gif` },
  { id: 'spatial_warp_almanac', name: 'Spatial Warp Almanac', type: 'loot', price: 0, sellPrice: 10000, soldTo: [NpcType.RASHID], description: 'A rare book from Oberon.', image: `${IMG_BASE}Spatial_Warp_Almanac.gif` },
];
