
import { Item, EquipmentSlot, NpcType, SkillType, Vocation, DamageType } from '../../types';
import { IMG_BASE } from '../config';

export const WANDS_LIST: Item[] = [
  // WANDS
  { id: 'wand_vortex', name: 'Wand of Vortex', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 13, defense: 0, price: 500, sellPrice: 100, soldTo: [NpcType.BLUE_DJINN, NpcType.TRADER], description: 'Energia básica (Lvl 8+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Vortex.gif` },
  { id: 'wand_dragonbreath', name: 'Wand of Dragonbreath', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 19, defense: 0, price: 1000, sellPrice: 200, soldTo: [NpcType.BLUE_DJINN], description: 'Fogo (Lvl 13+).', scalingStat: SkillType.MAGIC, damageType: DamageType.FIRE, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Dragonbreath.gif` },
  { id: 'wand_decay', name: 'Wand of Decay', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 30, defense: 0, price: 5000, sellPrice: 1000, soldTo: [NpcType.BLUE_DJINN], description: 'Morte (Lvl 19+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Decay.gif` },
  { id: 'wand_draconia', name: 'Wand of Draconia', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 35, defense: 0, price: 7500, sellPrice: 1500, soldTo: [NpcType.BLUE_DJINN], description: 'Fogo (Lvl 22+).', scalingStat: SkillType.MAGIC, damageType: DamageType.FIRE, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Draconia.gif` },
  { id: 'wand_cosmic_energy', name: 'Wand of Cosmic Energy', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 40, defense: 0, price: 10000, sellPrice: 2000, soldTo: [NpcType.BLUE_DJINN], description: 'Energia (Lvl 26+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Cosmic_Energy.gif` },
  { id: 'wand_inferno', name: 'Wand of Inferno', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 45, defense: 0, price: 15000, sellPrice: 3000, soldTo: [NpcType.BLUE_DJINN], description: 'Fogo puro (Lvl 33+).', scalingStat: SkillType.MAGIC, damageType: DamageType.FIRE, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Inferno.gif` },
  { id: 'wand_starstorm', name: 'Wand of Starstorm', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 0, price: 18000, sellPrice: 3600, soldTo: [NpcType.BLUE_DJINN], description: 'Energia pura (Lvl 42+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Starstorm.gif` },
  { id: 'wand_voodoo', name: 'Wand of Voodoo', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 0, price: 22000, sellPrice: 4400, soldTo: [NpcType.BLUE_DJINN], description: 'Morte (Lvl 42+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Voodoo.gif` },
  { id: 'wand_defiance', name: 'Wand of Defiance', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 55, defense: 0, price: 0, sellPrice: 6000, soldTo: [NpcType.RASHID], description: 'Esferas de Luz (Lvl 65+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Defiance.gif` },
  { id: 'dream_blossom_staff', name: 'Dream Blossom Staff', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 60, defense: 0, price: 0, sellPrice: 15000, soldTo: [NpcType.RASHID], description: 'Poder onírico (Lvl 80+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Dream_Blossom_Staff.gif` },
  { id: 'wand_destruction', name: 'Wand of Destruction', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 70, defense: 0, price: 0, sellPrice: 30000, soldTo: [NpcType.RASHID], description: 'Destruição Imbuída (Lvl 200+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Wand_of_Destruction.gif` },
  { id: 'lion_wand', name: 'Lion Wand', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 75, defense: 0, price: 0, sellPrice: 100000, soldTo: [NpcType.RASHID], description: 'Poder do Leão (Lvl 270+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Lion_Wand.gif` },
  { id: 'naga_wand', name: 'Naga Wand', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 78, defense: 0, price: 0, sellPrice: 120000, soldTo: [NpcType.RASHID], description: 'Magia Naga (Lvl 250+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Naga_Wand.gif` },
  { id: 'cobra_wand', name: 'Cobra Wand', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 80, defense: 0, price: 0, sellPrice: 150000, soldTo: [NpcType.RASHID], description: 'Veneno da Cobra (Lvl 270+).', scalingStat: SkillType.MAGIC, damageType: DamageType.FIRE, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Cobra_Wand.gif` },
  { id: 'falcon_wand', name: 'Falcon Wand', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 85, defense: 0, price: 0, sellPrice: 200000, soldTo: [NpcType.RASHID], description: 'Relíquia do Falcão (Lvl 300+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Falcon_Wand.gif` },
  { id: 'soultainter', name: 'Soultainter', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 95, defense: 0, price: 0, sellPrice: 500000, soldTo: [NpcType.RASHID], description: 'Ceifador de Almas (Lvl 400+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Soultainter.gif` },
  { id: 'sanguine_coil', name: 'Sanguine Coil', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 105, defense: 0, price: 0, sellPrice: 1000000, soldTo: [NpcType.RASHID], description: 'Espiral Sanguínea (Lvl 500+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Sanguine_Coil.gif` },
  { id: 'grand_sanguine_coil', name: 'Grand Sanguine Coil', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 120, defense: 0, price: 0, sellPrice: 5000000, soldTo: [NpcType.RASHID], description: 'Poder Supremo (Lvl 600+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, requiredVocation: [Vocation.SORCERER], image: `${IMG_BASE}Grand_Sanguine_Coil.gif` },
  { id: 'magic_light_wand', name: 'Magic Light Wand', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 35, defense: 0, price: 0, sellPrice: 120, soldTo: [NpcType.BLUE_DJINN], description: 'Varinha de luz (Sem Voc).', scalingStat: SkillType.MAGIC, damageType: DamageType.ENERGY, image: `${IMG_BASE}Magic_Light_Wand.gif` },

  // RODS
  { id: 'snake_bite', name: 'Snakebite Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 13, defense: 0, price: 500, sellPrice: 100, soldTo: [NpcType.BLUE_DJINN, NpcType.TRADER], description: 'Veneno básico (Lvl 8+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Snakebite_Rod.gif` },
  { id: 'moonlight_rod', name: 'Moonlight Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 19, defense: 0, price: 1000, sellPrice: 200, soldTo: [NpcType.BLUE_DJINN], description: 'Gelo (Lvl 13+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Moonlight_Rod.gif` },
  { id: 'necrotic_rod', name: 'Necrotic Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 30, defense: 0, price: 5000, sellPrice: 1000, soldTo: [NpcType.BLUE_DJINN], description: 'Morte (Lvl 19+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Necrotic_Rod.gif` },
  { id: 'northwind_rod', name: 'Northwind Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 35, defense: 0, price: 7500, sellPrice: 1500, soldTo: [NpcType.BLUE_DJINN], description: 'Gelo (Lvl 22+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Northwind_Rod.gif` },
  { id: 'terra_rod', name: 'Terra Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 40, defense: 0, price: 10000, sellPrice: 2000, soldTo: [NpcType.BLUE_DJINN], description: 'Terra (Lvl 26+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Terra_Rod.gif` },
  { id: 'springsprout_rod', name: 'Springsprout Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 42, defense: 0, price: 12000, sellPrice: 2400, soldTo: [NpcType.BLUE_DJINN], description: 'Terra e Vida (Lvl 27+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Springsprout_Rod.gif` },
  { id: 'hailstorm_rod', name: 'Hailstorm Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 45, defense: 0, price: 15000, sellPrice: 3000, soldTo: [NpcType.BLUE_DJINN], description: 'Tempestade de gelo (Lvl 33+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Hailstorm_Rod.gif` },
  { id: 'underworld_rod', name: 'Underworld Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 50, defense: 0, price: 22000, sellPrice: 4400, soldTo: [NpcType.BLUE_DJINN], description: 'Morte súbita (Lvl 42+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Underworld_Rod.gif` },
  { id: 'glacial_rod', name: 'Glacial Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 55, defense: 0, price: 0, sellPrice: 6000, soldTo: [NpcType.RASHID], description: 'Frio glacial (Lvl 65+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Glacial_Rod.gif` },
  { id: 'rod_destruction', name: 'Rod of Destruction', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 70, defense: 0, price: 0, sellPrice: 30000, soldTo: [NpcType.RASHID], description: 'Destruição Imbuída (Lvl 200+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Rod_of_Destruction.gif` },
  { id: 'cobra_rod', name: 'Cobra Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 80, defense: 0, price: 0, sellPrice: 150000, soldTo: [NpcType.RASHID], description: 'Veneno da Cobra (Lvl 270+).', scalingStat: SkillType.MAGIC, damageType: DamageType.DEATH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Cobra_Rod.gif` },
  { id: 'naga_rod', name: 'Naga Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 78, defense: 0, price: 0, sellPrice: 120000, soldTo: [NpcType.RASHID], description: 'Magia Naga (Lvl 250+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Naga_Rod.gif` },
  { id: 'lion_rod', name: 'Lion Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 75, defense: 0, price: 0, sellPrice: 100000, soldTo: [NpcType.RASHID], description: 'Força do Leão (Lvl 270+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Lion_Rod.gif` },
  { id: 'falcon_rod', name: 'Falcon Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 85, defense: 0, price: 0, sellPrice: 200000, soldTo: [NpcType.RASHID], description: 'Relíquia do Falcão (Lvl 300+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Falcon_Rod.gif` },
  { id: 'soulhexer', name: 'Soulhexer', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 95, defense: 0, price: 0, sellPrice: 500000, soldTo: [NpcType.RASHID], description: 'Feitiço de Almas (Lvl 400+).', scalingStat: SkillType.MAGIC, damageType: DamageType.ICE, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Soulhexer.gif` },
  { id: 'sanguine_rod', name: 'Sanguine Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 105, defense: 0, price: 0, sellPrice: 1000000, soldTo: [NpcType.RASHID], description: 'Vara Sanguínea (Lvl 500+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Sanguine_Rod.gif` },
  { id: 'grand_sanguine_rod', name: 'Grand Sanguine Rod', type: 'equipment', slot: EquipmentSlot.HAND_RIGHT, attack: 120, defense: 0, price: 0, sellPrice: 5000000, soldTo: [NpcType.RASHID], description: 'Natureza Suprema (Lvl 600+).', scalingStat: SkillType.MAGIC, damageType: DamageType.EARTH, requiredVocation: [Vocation.DRUID], image: `${IMG_BASE}Grand_Sanguine_Rod.gif` },
];
